CREATE TABLE [San_Pham] (
	Ma int NOT NULL,
	Ten varchar(255) NOT NULL,
  CONSTRAINT [PK_SAN_PHAM] PRIMARY KEY CLUSTERED
  (
  [Ma] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Ao] (
	Ma_Ao varchar(255) NOT NULL,
	Ma_San_Pham int NOT NULL,
	Ten_Ao varchar(255) NOT NULL,
	Ma_Co_Ao varchar(255) NOT NULL,
	Gia int NOT NULL,
	Ma_Noi_Nhap varchar(255) NOT NULL,
	Ngay_Nhap date NOT NULL,
	Ngay_Xuat date NOT NULL,
	So_Luong int NOT NULL,
	Ma_Chat_Lieu varchar(255) NOT NULL,
  CONSTRAINT [PK_AO] PRIMARY KEY CLUSTERED
  (
  [Ma_Ao] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Noi_Sx] (
	Ma varchar(255) NOT NULL,
	Ten varchar(255) NOT NULL,
	Dia_Chi varchar(255) NOT NULL,
	SDT varchar(255) NOT NULL,
	Gmail varchar(255) NOT NULL,
  CONSTRAINT [PK_NOI_SX] PRIMARY KEY CLUSTERED
  (
  [Ma] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Nhap_Hang] (
	Ma int NOT NULL,
	Ngay_Nhap date NOT NULL,
	Ma_San_Pham int NOT NULL,
	Ma_Noi_Sx varchar(255) NOT NULL,
	So_Luong int NOT NULL,
	Gia int NOT NULL,
  CONSTRAINT [PK_NHAP_HANG] PRIMARY KEY CLUSTERED
  (
  [Ma] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Co_Ao] (
	Ma_Co varchar(255) NOT NULL,
	Co varchar(255) NOT NULL,
	So_Luong int NOT NULL,
  CONSTRAINT [PK_CO_AO] PRIMARY KEY CLUSTERED
  (
  [Ma_Co] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Khach_Hang] (
	Ma int NOT NULL,
	Ten varchar(255) NOT NULL,
	SDT varchar(255) NOT NULL,
	Dia_Chi varchar(255) NOT NULL,
  CONSTRAINT [PK_KHACH_HANG] PRIMARY KEY CLUSTERED
  (
  [Ma] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Xuat_Hang] (
	Ma int NOT NULL,
	Ma_Ao varchar(255) NOT NULL,
	Ngay_Ban date NOT NULL,
	So_Luong int NOT NULL,
	Don_Gia int NOT NULL,
	Ma_Khach_Hang int NOT NULL,
  CONSTRAINT [PK_XUAT_HANG] PRIMARY KEY CLUSTERED
  (
  [Ma] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Chat_Lieu] (
	Ma varchar(255) NOT NULL,
	Ten varchar(255) NOT NULL,
	So_Luong int NOT NULL,
  CONSTRAINT [PK_CHAT_LIEU] PRIMARY KEY CLUSTERED
  (
  [Ma] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO

ALTER TABLE [Ao] WITH CHECK ADD CONSTRAINT [Ao_fk0] FOREIGN KEY ([Ma_San_Pham]) REFERENCES [San_Pham]([Ma])
ON UPDATE CASCADE
GO
ALTER TABLE [Ao] CHECK CONSTRAINT [Ao_fk0]
GO
ALTER TABLE [Ao] WITH CHECK ADD CONSTRAINT [Ao_fk1] FOREIGN KEY ([Ma_Co_Ao]) REFERENCES [Co_Ao]([Ma_Co])
ON UPDATE CASCADE
GO
ALTER TABLE [Ao] CHECK CONSTRAINT [Ao_fk1]
GO
ALTER TABLE [Ao] WITH CHECK ADD CONSTRAINT [Ao_fk2] FOREIGN KEY ([Ma_Noi_Nhap]) REFERENCES [Noi_Sx]([Ma])
ON UPDATE CASCADE
GO
ALTER TABLE [Ao] CHECK CONSTRAINT [Ao_fk2]
GO
ALTER TABLE [Ao] WITH CHECK ADD CONSTRAINT [Ao_fk3] FOREIGN KEY ([Ma_Chat_Lieu]) REFERENCES [Chat_Lieu]([Ma])
ON UPDATE CASCADE
GO
ALTER TABLE [Ao] CHECK CONSTRAINT [Ao_fk3]
GO


ALTER TABLE [Nhap_Hang] WITH CHECK ADD CONSTRAINT [Nhap_Hang_fk0] FOREIGN KEY ([Ma_San_Pham]) REFERENCES [San_Pham]([Ma])
ON UPDATE CASCADE
GO
ALTER TABLE [Nhap_Hang] CHECK CONSTRAINT [Nhap_Hang_fk0]
GO
ALTER TABLE [Nhap_Hang] WITH CHECK ADD CONSTRAINT [Nhap_Hang_fk1] FOREIGN KEY ([Ma_Noi_Sx]) REFERENCES [Noi_Sx]([Ma])
ON UPDATE CASCADE
GO
ALTER TABLE [Nhap_Hang] CHECK CONSTRAINT [Nhap_Hang_fk1]
GO



ALTER TABLE [Xuat_Hang] WITH CHECK ADD CONSTRAINT [Xuat_Hang_fk0] FOREIGN KEY ([Ma_Ao]) REFERENCES [Ao]([Ma_Ao])
ON UPDATE CASCADE
GO
ALTER TABLE [Xuat_Hang] CHECK CONSTRAINT [Xuat_Hang_fk0]
GO
ALTER TABLE [Xuat_Hang] WITH CHECK ADD CONSTRAINT [Xuat_Hang_fk1] FOREIGN KEY ([Ma_Khach_Hang]) REFERENCES [Khach_Hang]([Ma])
ON UPDATE CASCADE
GO
ALTER TABLE [Xuat_Hang] CHECK CONSTRAINT [Xuat_Hang_fk1]
GO


