package EX1;

import com.context.DBContext;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dell
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    DBContext a = new DBContext();
    Statement stm;// thực thi câu lệnh sql
    ResultSet rs;//Lưu trữ và xử lý dữ liệu

    public Register() {
        initComponents();
        stm = a.connectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_account = new javax.swing.JLabel();
        jTextField_account = new javax.swing.JTextField();
        jLabel_name = new javax.swing.JLabel();
        jLabel_dob = new javax.swing.JLabel();
        jCheckBox_male = new javax.swing.JCheckBox();
        jCheckBox_female = new javax.swing.JCheckBox();
        jTextField_name = new javax.swing.JTextField();
        jLabel_gender1 = new javax.swing.JLabel();
        jTextField_address = new javax.swing.JTextField();
        jLabel_address = new javax.swing.JLabel();
        jTextField_dob = new javax.swing.JTextField();
        jLabel_passwd1 = new javax.swing.JLabel();
        jPasswordField_passwd1 = new javax.swing.JPasswordField();
        jLabel_repasswd = new javax.swing.JLabel();
        jPasswordField_repasswd = new javax.swing.JPasswordField();
        jButton_create = new javax.swing.JButton();
        jButton_reset2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel1.setText("Registration");

        jLabel_account.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel_account.setText("Account: ");

        jTextField_account.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_accountMouseClicked(evt);
            }
        });
        jTextField_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_accountActionPerformed(evt);
            }
        });
        jTextField_account.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_accountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_accountKeyReleased(evt);
            }
        });

        jLabel_name.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel_name.setText("Name:");

        jLabel_dob.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel_dob.setText("Date of birth:");

        jCheckBox_male.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        jCheckBox_male.setText("Male");
        jCheckBox_male.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_maleMouseClicked(evt);
            }
        });

        jCheckBox_female.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        jCheckBox_female.setText("Female");
        jCheckBox_female.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_femaleMouseClicked(evt);
            }
        });

        jTextField_name.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_nameMouseClicked(evt);
            }
        });
        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyReleased(evt);
            }
        });

        jLabel_gender1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel_gender1.setText("Gender:");

        jTextField_address.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_addressMouseClicked(evt);
            }
        });
        jTextField_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addressActionPerformed(evt);
            }
        });
        jTextField_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_addressKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_addressKeyReleased(evt);
            }
        });

        jLabel_address.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel_address.setText("Address:");

        jTextField_dob.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_dob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_dobMouseClicked(evt);
            }
        });
        jTextField_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_dobActionPerformed(evt);
            }
        });
        jTextField_dob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_dobKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_dobKeyReleased(evt);
            }
        });

        jLabel_passwd1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel_passwd1.setText("Password:");

        jPasswordField_passwd1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPasswordField_passwd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_passwd1MouseClicked(evt);
            }
        });
        jPasswordField_passwd1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_passwd1KeyPressed(evt);
            }
        });

        jLabel_repasswd.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel_repasswd.setText("Re-Password:");

        jPasswordField_repasswd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPasswordField_repasswd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_repasswdMouseClicked(evt);
            }
        });
        jPasswordField_repasswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_repasswdKeyPressed(evt);
            }
        });

        jButton_create.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton_create.setText("Register");
        jButton_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createActionPerformed(evt);
            }
        });

        jButton_reset2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton_reset2.setText("Reset");
        jButton_reset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_reset2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_account)
                                    .addComponent(jLabel_name)
                                    .addComponent(jLabel_dob)
                                    .addComponent(jLabel_gender1)
                                    .addComponent(jLabel_address)
                                    .addComponent(jLabel_passwd1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jPasswordField_passwd1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(137, 137, 137)
                                            .addComponent(jCheckBox_female))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField_dob, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                                .addComponent(jCheckBox_male)
                                                .addComponent(jTextField_name)
                                                .addComponent(jTextField_account)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_repasswd)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField_repasswd))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton_create)
                        .addGap(88, 88, 88)
                        .addComponent(jButton_reset2)))
                .addGap(31, 87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_account, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_name)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_male)
                    .addComponent(jCheckBox_female)
                    .addComponent(jLabel_gender1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_dob)
                    .addComponent(jTextField_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_address)
                    .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_passwd1)
                    .addComponent(jPasswordField_passwd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_repasswd)
                    .addComponent(jPasswordField_repasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_create)
                    .addComponent(jButton_reset2))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_accountMouseClicked

    }//GEN-LAST:event_jTextField_accountMouseClicked

    private void jTextField_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_accountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_accountActionPerformed

    private void jTextField_accountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_accountKeyPressed

    }//GEN-LAST:event_jTextField_accountKeyPressed

    private void jTextField_accountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_accountKeyReleased

    }//GEN-LAST:event_jTextField_accountKeyReleased

    private void jCheckBox_maleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_maleMouseClicked

    }//GEN-LAST:event_jCheckBox_maleMouseClicked

    private void jCheckBox_femaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_femaleMouseClicked

    }//GEN-LAST:event_jCheckBox_femaleMouseClicked

    private void jTextField_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_nameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameMouseClicked

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void jTextField_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameKeyPressed

    private void jTextField_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameKeyReleased

    private void jTextField_addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_addressMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addressMouseClicked

    private void jTextField_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addressActionPerformed

    private void jTextField_addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_addressKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addressKeyPressed

    private void jTextField_addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_addressKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addressKeyReleased

    private void jTextField_dobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_dobMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_dobMouseClicked

    private void jTextField_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_dobActionPerformed

    private void jTextField_dobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_dobKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_dobKeyPressed

    private void jTextField_dobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_dobKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_dobKeyReleased

    private void jPasswordField_passwd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_passwd1MouseClicked

    }//GEN-LAST:event_jPasswordField_passwd1MouseClicked

    private void jPasswordField_passwd1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_passwd1KeyPressed

    }//GEN-LAST:event_jPasswordField_passwd1KeyPressed

    private void jPasswordField_repasswdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_repasswdMouseClicked

    }//GEN-LAST:event_jPasswordField_repasswdMouseClicked

    private void jPasswordField_repasswdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_repasswdKeyPressed

    }//GEN-LAST:event_jPasswordField_repasswdKeyPressed

    private void jButton_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createActionPerformed
        try {
            String user = jTextField_account.getText().trim();
            String pass = jPasswordField_passwd1.getText().trim();
            String re_pass = jPasswordField_repasswd.getText().trim();
            String name = jTextField_name.getText().trim();
            boolean male = jCheckBox_male.isSelected();
            boolean female = jCheckBox_female.isSelected();
            String address = jTextField_address.getText().trim();
            String dob = jTextField_dob.getText().trim();
            if (checkEmptyFormCreateAccount()) {
                JOptionPane.showMessageDialog(rootPane, "Text field and checkbox can't be blank");

            } else {
                if (checkValidFormCreateAccount() == 0) {
                    JOptionPane.showMessageDialog(rootPane, "format of account only contains one and more alphabet character with space");

                } else if (checkValidFormCreateAccount() == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Be at least eight characters in length\n"
                            + "Contain characters from three of the following four categories:\n"
                            + "English uppercase characters (A through Z)\n"
                            + "English lowercase characters (a through z)\n"
                            + "Base 10 digits (0 through 9)\n"
                            + "Non-alphabetic characters (for example, !, $, #, %)");

                } else if (checkValidFormCreateAccount() == 2) {
                    JOptionPane.showMessageDialog(rootPane, "password can't be diffent from repassword");

                } else if (checkValidFormCreateAccount() == 3) {
                    JOptionPane.showMessageDialog(rootPane, "name only contains character alphabet");

                } else if (checkValidFormCreateAccount() == 4) {
                    JOptionPane.showMessageDialog(rootPane, "person can't be both male and female");

                } else if (checkValidFormCreateAccount() == 5) {
                    JOptionPane.showMessageDialog(rootPane, "format of address only contains one and more alphabet character with space");

                } else if (checkValidFormCreateAccount() == 6) {
                    JOptionPane.showMessageDialog(rootPane, "format of dat of birth like YYYY-MM-DD");

                } else {
                    int bit;
                    if (male) {
                        bit = 1;
                    } else {
                        bit = 0;
                    }
                    String insert = "INSERT INTO tblUser VALUES('" + user + "','" + pass + "','" + name + "','" + bit + "','" + address + "','" + dob + "');";
                    stm.execute(insert);
                    this.dispose();
                    JOptionPane.showMessageDialog(rootPane, "Make account successfully, now you are able to login");

                }

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_createActionPerformed

    private void jButton_reset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_reset2ActionPerformed
        jTextField_account.setText("");
        jPasswordField_passwd1.setText("");
        jPasswordField_repasswd.setText("");
        jTextField_name.setText("");
        jTextField_dob.setText("");
        jTextField_address.setText("");
        jCheckBox_male.setSelected(false);
        jCheckBox_female.setSelected(false);
    }//GEN-LAST:event_jButton_reset2ActionPerformed
    public boolean checkValidAccount(JTextField text) {
        String txt = text.getText().trim();
        if (txt.matches("[a-zA-Z]+([0-9]+)?")) {
            return true;
        }

        return false;
    }

    public boolean checkEmptyFormCreateAccount() {

        boolean account_empty = jTextField_account.getText().isEmpty();
        boolean pass_empty = jPasswordField_passwd1.getText().isEmpty();
        boolean re_pass_empty = jPasswordField_repasswd.getText().isEmpty();
        boolean name_empty = jTextField_name.getText().isEmpty();
        boolean male_empty = jCheckBox_male.isSelected();
        boolean female_empty = jCheckBox_female.isSelected();
        boolean dob_empty = jTextField_dob.getText().isEmpty();
        boolean address_empty = jTextField_address.getText().isEmpty();
        if (!account_empty && !pass_empty && !re_pass_empty && !name_empty && !male_empty && female_empty && !dob_empty && !address_empty || !account_empty && !pass_empty && !re_pass_empty && !name_empty && male_empty && !female_empty && !dob_empty && !address_empty || !account_empty && !pass_empty && !re_pass_empty && !name_empty && male_empty && female_empty && !dob_empty && !address_empty) {
            return false;
        }
        return true;
    }

    public boolean checkStrongForPassWord(JPasswordField password) {

        if (!password.getText().trim().matches("(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}")) {
            return false;
        }

        return true;
    }

    public int checkValidFormCreateAccount() {
        // valid account
        boolean valid_account = checkValidAccount(jTextField_account);
        if (!valid_account) {
            return 0;
        }
        // check strong password
        if (!checkStrongForPassWord(jPasswordField_passwd1)) {
            return 1;
        }
        // valid same pass and repass
        if (!jPasswordField_passwd1.getText().trim().equals(jPasswordField_repasswd.getText().trim())) {
            return 2;
        }
        // valid name
        boolean valid_name = jTextField_name.getText().trim().matches("[a-zA-Z ]+");
        if (!valid_name) {
            return 3;
        }
        // valid gender
        boolean male_empty = jCheckBox_male.isSelected();
        boolean female_empty = jCheckBox_female.isSelected();
        if (female_empty && male_empty) {
            return 4;
        }
        // valid address
        boolean valid_address = checkValidAccount(jTextField_address);
        if (!valid_address) {
            return 5;
        }
        // valid dob
        boolean valid_dob = jTextField_dob.getText().trim().matches("^\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])$");
        if (!valid_dob) {
            return 6;
        }
        return 7;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_create;
    private javax.swing.JButton jButton_reset2;
    private javax.swing.JCheckBox jCheckBox_female;
    private javax.swing.JCheckBox jCheckBox_male;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_account;
    private javax.swing.JLabel jLabel_address;
    private javax.swing.JLabel jLabel_dob;
    private javax.swing.JLabel jLabel_gender1;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_passwd1;
    private javax.swing.JLabel jLabel_repasswd;
    private javax.swing.JPasswordField jPasswordField_passwd1;
    private javax.swing.JPasswordField jPasswordField_repasswd;
    private javax.swing.JTextField jTextField_account;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_dob;
    private javax.swing.JTextField jTextField_name;
    // End of variables declaration//GEN-END:variables
}
