// ======= DO NOT EDIT THIS FILE ============
class Car
 {String owner;
  int color;
  int size;

    public Car(String owner, int color, int size) {
        this.owner = owner;
        this.color = color;
        this.size = size;
    }
  
  public String toString()
   {return("("+owner+ "  "+ color + "   "+size+")");
   }
 }
