package q2;
import java.util.ArrayList;
/*
 * DO NOT EDIT THIS FILE
 */
public interface IInvoice { 
    /*
      Firstly, sort the list of invoice “a” ascending by customer name (alphabet order),
     *finally, return the customer name of second invoice in the list “a”. 
     */
    public String f1(ArrayList<Invoice> a);        
   
    /*
      Firstly, remove 2 invoices which are highest amount in the list “a”, 
     *finally calculate and return the sum of amount of all other invoices in the list “a”. 
     */
    public int f2(ArrayList<Invoice> a);
}
