/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.sun.glass.events.KeyEvent;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Phong Khoang
 */
public class GenerateNumber extends javax.swing.JFrame {

    /**
     * Creates new form GenerateNumber
     */
    class MyThread1 extends Thread{
        volatile boolean isRun = false;
        
        public void execute(){
            isRun = true;
        }
        
        public void myStop(){
            isRun = false;
        }

        @Override
        public void run() {
            int low = 10, high = 100;
            
            try{
                while(true){
                    if(isRun){
                        // 1. tao so nguyen ngau nhien [low-high]
                        int num = new Random().nextInt(high-low+1) + low;
                        // 2. day so vua tao len jList
                        dlm.addElement(num);
                        
                        // nghi 1s
                        Thread.sleep(1000);
                    }
                } 
            } catch (InterruptedException ex) {
                Logger.getLogger(SlideText.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    class MyThread2 extends Thread{
        
        
        List<Object> listNum;

        public MyThread2(List<Object> listNum) {
            this.listNum = listNum;
        }

        public MyThread2() {
        }
        
        public void setListNum(List<Object> listNum){
            this.listNum = listNum;
        }
  
        volatile boolean isRun = false;

        public void execute(){
            isRun = true;
        }
        
        public void myStop(){
            isRun = false;
        }

        @Override
        public void run() {
            int low = 10, high = 100;
            // index : 0, 1, 2, 3, 4
            // lít   : 2, 6, 1, 9
          
            int index = 0;
            try{
                while(true){
                    if(isRun){
                        int size = listNum.size();
                        if(index >= size){
                            index = 0;
                        }
                        
                        // show num at index to jLabel
                        labelShowNum.setText(listNum.get(index).toString());
                        // tang index len 1 don vi
                        index++;
                        
                        // nghi 1s
                        Thread.sleep(1000);
                    }
                } 
            } catch (InterruptedException ex) {
                Logger.getLogger(SlideText.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    // tao thread 1
    MyThread1 t1 = null;
    MyThread2 t2 = null;
    
    // ban mem hon de quan ly data cua 1 JList cung
    DefaultListModel<Object> dlm;
    
    public GenerateNumber() {
        initComponents();
        // khoi tao dlm
        dlm = new DefaultListModel<>();
        // set model cho JList
        jListNum.setModel(dlm);
        
        // khoi tao thread 
        t1 = new MyThread1();
        t2 = new MyThread2();
        // "chuan bi chay"
        t1.start();
        t2.start();
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblDisplayNum = new javax.swing.JLabel();
        rdGenerate = new javax.swing.JRadioButton();
        rdStop = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNum = new javax.swing.JList();
        btnShow = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelShowNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup2.add(rdGenerate);
        rdGenerate.setText("Generate");
        rdGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdGenerateActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdStop);
        rdStop.setText("Stop");
        rdStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdStopActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListNum);

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdGenerate)
                                .addGap(35, 35, 35)
                                .addComponent(rdStop))
                            .addComponent(lblDisplayNum, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnShow)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(labelShowNum, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblDisplayNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdGenerate)
                            .addComponent(rdStop))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelShowNum, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(btnShow)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdGenerateActionPerformed
        // TODO add your handling code here:
        // xoa toan bo du lieu cu cua jlist
        dlm.clear();       
       // dung thread 2
        t2.myStop();     
        t1.execute();
    }//GEN-LAST:event_rdGenerateActionPerformed

    private void rdStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdStopActionPerformed
        // TODO add your handling code here:
        t1.myStop();
    }//GEN-LAST:event_rdStopActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        // lay tat ca cac item dc chon tu jList
        List<Object> listSelectedNum = jListNum.getSelectedValuesList();
        // kiem tra neu chua chon item nao thi dung
        if(listSelectedNum.isEmpty()) return;
        
       
        t2.setListNum(listSelectedNum);
        t2.execute();
        
        
        
//        // in ra man hinh
//        for(Object obj: listSelectedNum){
//            System.out.println(obj.toString());
//        }
    }//GEN-LAST:event_btnShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateNumber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShow;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListNum;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelShowNum;
    private javax.swing.JLabel lblDisplayNum;
    private javax.swing.JRadioButton rdGenerate;
    private javax.swing.JRadioButton rdStop;
    // End of variables declaration//GEN-END:variables
}
