package EX1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.context.DBContext;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author dell
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    DBContext a = new DBContext();
    Statement stm;// thực thi câu lệnh sql
    ResultSet rs;//Lưu trữ và xử lý dữ liệu
    public Login() {
        initComponents();
        stm = a.connectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_account = new javax.swing.JLabel();
        jTextField_account = new javax.swing.JTextField();
        jLabel_passwd = new javax.swing.JLabel();
        jPasswordField_passwd = new javax.swing.JPasswordField();
        jButton_login = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jButton_register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_account.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel_account.setText("Account: ");

        jTextField_account.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_accountMouseClicked(evt);
            }
        });
        jTextField_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_accountActionPerformed(evt);
            }
        });
        jTextField_account.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_accountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_accountKeyReleased(evt);
            }
        });

        jLabel_passwd.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel_passwd.setText("Password:");

        jPasswordField_passwd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPasswordField_passwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_passwdMouseClicked(evt);
            }
        });
        jPasswordField_passwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_passwdKeyPressed(evt);
            }
        });

        jButton_login.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton_login.setText("Login");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        jButton_reset.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton_reset.setText("Reset");
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });

        jButton_register.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton_register.setText("Register");
        jButton_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_login)
                        .addGap(44, 44, 44)
                        .addComponent(jButton_reset)
                        .addGap(34, 34, 34)
                        .addComponent(jButton_register))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_passwd)
                                .addGap(25, 25, 25)
                                .addComponent(jPasswordField_passwd, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_account)
                                .addGap(35, 35, 35)
                                .addComponent(jTextField_account, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_account, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_passwd)
                    .addComponent(jPasswordField_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_login)
                    .addComponent(jButton_reset)
                    .addComponent(jButton_register))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_accountMouseClicked
   
    }//GEN-LAST:event_jTextField_accountMouseClicked

    private void jTextField_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_accountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_accountActionPerformed

    private void jTextField_accountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_accountKeyPressed

    }//GEN-LAST:event_jTextField_accountKeyPressed

    private void jTextField_accountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_accountKeyReleased

    }//GEN-LAST:event_jTextField_accountKeyReleased

    private void jPasswordField_passwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_passwdMouseClicked
    
    }//GEN-LAST:event_jPasswordField_passwdMouseClicked

    private void jPasswordField_passwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_passwdKeyPressed
        
    }//GEN-LAST:event_jPasswordField_passwdKeyPressed
    public boolean checkEmptyFormLogin() {

        if (!jTextField_account.getText().isEmpty() && !jPasswordField_passwd.getText().isEmpty()) {
            return false;
        }

        return true;

    }
      public boolean checkValidAccount(JTextField text) {
        String txt = text.getText().trim();
        if (txt.matches("[a-zA-Z]+([0-9]+)?")) {
            return true;
        }

        return false;
    }
    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        // check account va password co trong bang tbl user ko neu co thi login thanh cong
        // nguoc lai thi bien
        try {
            String user = jTextField_account.getText().trim();
            String password = jPasswordField_passwd.getText().trim();
            if (checkEmptyFormLogin()) {
                JOptionPane.showMessageDialog(rootPane, "Text field can't be blank");
               
            } else {
                if (checkValidAccount(jTextField_account)) {
                    rs = stm.executeQuery("Select * from tblUser where account='" + user + "'");
                    if (rs.first()) {
                        JOptionPane.showMessageDialog(rootPane, "Login successfully");
                        ProductAndCustomer pc = new ProductAndCustomer();
                        pc.setLocationRelativeTo(null);
                        pc.setVisible(true);
                       
                    } else {

                        JOptionPane.showMessageDialog(rootPane, "Login fail");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "format of account only contains alphabet character or number");
                    
                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_loginActionPerformed

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
        jTextField_account.setText("");
        jPasswordField_passwd.setText("");
       
    }//GEN-LAST:event_jButton_resetActionPerformed

    private void jButton_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registerActionPerformed
       Register ri = new Register();
       ri.setLocationRelativeTo(null);
       ri.setVisible(true);
    }//GEN-LAST:event_jButton_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      Login lg = new Login();
      lg.setLocationRelativeTo(null);
      lg.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_login;
    private javax.swing.JButton jButton_register;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JLabel jLabel_account;
    private javax.swing.JLabel jLabel_passwd;
    private javax.swing.JPasswordField jPasswordField_passwd;
    private javax.swing.JTextField jTextField_account;
    // End of variables declaration//GEN-END:variables
}
