import java.awt.Color;
import javax.swing.*;
public class MainForm extends javax.swing.JFrame {
ProductForm frmProduct;
    /**
     * Creates new form frmMenuDemo
     */
    public MainForm() {
        initComponents();
        frmProduct = new ProductForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        menuItemRed = new javax.swing.JMenuItem();
        menuItemBlue = new javax.swing.JMenuItem();
        menuItemYellow = new javax.swing.JMenuItem();
        panelMain = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemOpen = new javax.swing.JMenuItem();
        menuItemNew = new javax.swing.JMenuItem();
        menuSaveAs = new javax.swing.JMenu();
        menuItemTextFile = new javax.swing.JMenuItem();
        menuItemPDFFile = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenu();

        menuItemRed.setText("Red");
        menuItemRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRedActionPerformed(evt);
            }
        });
        popupMenu.add(menuItemRed);

        menuItemBlue.setText("Blue");
        menuItemBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBlueActionPerformed(evt);
            }
        });
        popupMenu.add(menuItemBlue);

        menuItemYellow.setText("Yellow");
        menuItemYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemYellowActionPerformed(evt);
            }
        });
        popupMenu.add(menuItemYellow);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setComponentPopupMenu(popupMenu);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        menuFile.setText("File");
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });

        menuItemOpen.setText("Open");
        menuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOpenActionPerformed(evt);
            }
        });
        menuFile.add(menuItemOpen);

        menuItemNew.setText("New");
        menuFile.add(menuItemNew);

        menuSaveAs.setText("Save as ...");

        menuItemTextFile.setText("Text File");
        menuItemTextFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTextFileActionPerformed(evt);
            }
        });
        menuSaveAs.add(menuItemTextFile);

        menuItemPDFFile.setText("PDF file");
        menuSaveAs.add(menuItemPDFFile);

        menuFile.add(menuSaveAs);

        menuBar.add(menuFile);

        menuEdit.setText("Edit");
        menuBar.add(menuEdit);

        menuExit.setText("Exit");
        menuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExitMouseClicked(evt);
            }
        });
        menuBar.add(menuExit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemTextFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTextFileActionPerformed
JOptionPane.showMessageDialog(null, "Text file selected");
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemTextFileActionPerformed

    private void menuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExitMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_menuExitMouseClicked

    private void menuItemRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRedActionPerformed
panelMain.setBackground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemRedActionPerformed

    private void menuItemBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBlueActionPerformed
panelMain.setBackground(Color.blue);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemBlueActionPerformed

    private void menuItemYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemYellowActionPerformed
panelMain.setBackground(Color.yellow);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemYellowActionPerformed

    private void menuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenActionPerformed
frmProduct.setVisible(true);
//panelMain.add(t);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemOpenActionPerformed

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemBlue;
    private javax.swing.JMenuItem menuItemNew;
    private javax.swing.JMenuItem menuItemOpen;
    private javax.swing.JMenuItem menuItemPDFFile;
    private javax.swing.JMenuItem menuItemRed;
    private javax.swing.JMenuItem menuItemTextFile;
    private javax.swing.JMenuItem menuItemYellow;
    private javax.swing.JMenu menuSaveAs;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
}
