import java.awt.Color;
import javax.swing.JFileChooser;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.io.*;
public class SplitPaneDemo extends javax.swing.JFrame {
     final JColorChooser cc= new JColorChooser();
     final JFileChooser fc= new JFileChooser();
    /** Creates new form SplitPaneDemo */
    public SplitPaneDemo() {
        initComponents();
        this.setSize(400,300);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnBackColor = new javax.swing.JButton();
        btnOpenFile = new javax.swing.JButton();
        btnForColor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuOpen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mnuExit = new javax.swing.JMenuItem();
        mnuColor = new javax.swing.JMenu();
        mnuBackColor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        mnuForeColor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SplitPane Demo");
        getContentPane().setLayout(null);

        jSplitPane1.setDividerLocation(120);

        jPanel1.setLayout(null);

        btnBackColor.setText("BackColor");
        btnBackColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackColorActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackColor);
        btnBackColor.setBounds(10, 80, 100, 30);

        btnOpenFile.setText("Open file");
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpenFile);
        btnOpenFile.setBounds(10, 40, 100, 30);

        btnForColor.setText("ForeColor");
        btnForColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForColorActionPerformed(evt);
            }
        });
        jPanel1.add(btnForColor);
        btnForColor.setBounds(10, 120, 100, 30);

        jSplitPane1.setLeftComponent(jPanel1);

        txtContent.setColumns(20);
        txtContent.setRows(5);
        jScrollPane1.setViewportView(txtContent);

        jSplitPane1.setRightComponent(jScrollPane1);

        getContentPane().add(jSplitPane1);
        jSplitPane1.setBounds(0, 0, 390, 290);

        mnuFile.setText("File");

        mnuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        mnuOpen.setText("Open");
        mnuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpenActionPerformed(evt);
            }
        });
        mnuFile.add(mnuOpen);
        mnuFile.add(jSeparator1);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        jMenuBar1.add(mnuFile);

        mnuColor.setText("Color");

        mnuBackColor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        mnuBackColor.setText("Backcolor");
        mnuBackColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBackColorActionPerformed(evt);
            }
        });
        mnuColor.add(mnuBackColor);
        mnuColor.add(jSeparator2);

        mnuForeColor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        mnuForeColor.setText("Forecolor");
        mnuForeColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuForeColorActionPerformed(evt);
            }
        });
        mnuColor.add(mnuForeColor);

        jMenuBar1.add(mnuColor);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpenActionPerformed
        // Select and open a file
        try {
            int result= fc.showOpenDialog(this);
            if (result==JFileChooser.APPROVE_OPTION)
            {  File f= fc.getSelectedFile();
               if (f.isFile()) {
                 FileReader fr= new FileReader(f);
                 BufferedReader bf=new BufferedReader(fr);
                 this.txtContent.setText("");
                 String S, content="";
                 while((S=bf.readLine())!=null) content += S + "\n";
                 txtContent.setText(content);
                 bf.close(); fr.close();
               }
               else{
                   JOptionPane.showMessageDialog(this,"Folder!","MESSAGE",
                                              JOptionPane.INFORMATION_MESSAGE);
               }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e, "Attention!",
                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnuOpenActionPerformed

    private void mnuBackColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBackColorActionPerformed
        // TODO add your handling code here:
        Color c= cc.showDialog(this, "Select a color", Color.WHITE);
        txtContent.setBackground(c);
    }//GEN-LAST:event_mnuBackColorActionPerformed

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        // TODO add your handling code here:
        mnuOpenActionPerformed(null);
    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuForeColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuForeColorActionPerformed
        // TODO add your handling code here:
        Color c= cc.showDialog(this, "Select a color", Color.BLACK);
        txtContent.setForeground(c);
    }//GEN-LAST:event_mnuForeColorActionPerformed

    private void btnForColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForColorActionPerformed
        // TODO add your handling code here:
        mnuForeColorActionPerformed(null);
    }//GEN-LAST:event_btnForColorActionPerformed

    private void btnBackColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackColorActionPerformed
        // TODO add your handling code here:
         mnuBackColorActionPerformed(null);
    }//GEN-LAST:event_btnBackColorActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplitPaneDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackColor;
    private javax.swing.JButton btnForColor;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenuItem mnuBackColor;
    private javax.swing.JMenu mnuColor;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuForeColor;
    private javax.swing.JMenuItem mnuOpen;
    private javax.swing.JTextArea txtContent;
    // End of variables declaration//GEN-END:variables

}
