using HE130510_HuyNguyen_Lab1.BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HE130510_HuyNguyen_Lab1
{
    class Program
    {
        static void Main(string[] args)
        {
            string borrowNumber = "";
            string name = "";
            string sex = "";
            string address = "";
            string tel = "";
            string email = "";
            List<Borrowers> list = new List<Borrowers>();

            string bookNumber = "";
            string title = "";
            string author = "";
            string publisher = "";
            string copyNumber = "";
            string sequenceNumber = "";
            string type = "";
            float price = 0;
            string p = price.ToString();
            List<Book> listBook = new List<Book>();
            List<BookCopies> listBookCopies = new List<BookCopies>();
            string yn = "";
            string count;
            int c = 0;
            int count1 = 0;
            int count2 = 0;
            int count3 = 0;
            int count4 = 0;

            while (c < 4)
            {
                Console.Clear();
                Console.WriteLine("Lab 1: Nguyên Quang Huy, HE130510, SE1315");
                Console.WriteLine("MENU");
                Console.WriteLine("1. Add a new borrower");
                Console.WriteLine("2. Add a new book and its copies");
                Console.WriteLine("3. Exit");
                Console.Write("Please enter: 1, 2 or 3: ");

                count = Console.ReadLine();
                Int32.TryParse(count, out c);

                switch (c)
                {
                    case 1:
                        Console.WriteLine("You choice option 1");
                        Console.WriteLine("Borrow Number (generated by system): {0}", count1 + 1);
                        count1++;
                        borrowNumber = count1.ToString();
                        Console.Write("Enter Name: ");
                        name = Console.ReadLine();
                        while (name.Equals(""))
                        {
                            Console.WriteLine("Must not be empty. Try again!");
                            Console.Write("Enter Name: ");
                            name = Console.ReadLine();
                        }
                        Console.Write("Enter Sex (M/F): ");
                        sex = Console.ReadLine();
                        while (!sex.Equals("M") || !sex.Equals("F"))
                        {
                            if (sex.Equals("M") || sex.Equals("F"))
                                break;
                            Console.WriteLine("Must be M or F. Try again!");
                            Console.Write("Enter Sex (M/F): ");
                            sex = Console.ReadLine();

                        }
                        Console.Write("Enter Address (optional): ");
                        address = Console.ReadLine();
                        Console.Write("Enter Telephone (optional): ");
                        tel = Console.ReadLine();
                        Console.Write("Enter Email (optional): ");
                        email = Console.ReadLine();

                        BorrowerBL.addBorrower(list, borrowNumber, name, sex, address, tel, email);

                        Console.WriteLine("List of borrowers");
                        Console.WriteLine("Number   Name     Sex   Email");
                        foreach (Borrowers b in list)
                        {
                            Console.WriteLine("  {0}      {1}         {2}       {3}", b.BorrowNumber, b.Name, b.Sex, b.Email);
                        }
                        Console.ReadKey();

                        break;

                    case 2:
                        Console.WriteLine("You choice option 2");
                        Console.WriteLine("Book Number (generated by system): {0}", count3+1);
                        count3++;
                        bookNumber = count3.ToString();
                        Console.Write("Enter Title: ");
                        title = Console.ReadLine();
                        while (title.Equals(""))
                        {
                            Console.WriteLine("Must not be empty. Try again!");
                            Console.Write("Enter Title: ");
                            title = Console.ReadLine();
                        }
                        Console.Write("Enter Author (optional): ");
                        author = Console.ReadLine();
                        Console.Write("Enter Publisher (optional): ");
                        publisher = Console.ReadLine();

                        BookBL.addBook(listBook, bookNumber, title, author, publisher);

                        Console.WriteLine("Copy Number (generated by system): {0}", count2+1);
                        count2++;
                        copyNumber = count2.ToString();
                        Console.WriteLine("Enter sequence number: {0}", count4 + 1);
                        count4++;
                        sequenceNumber = count4.ToString();
                        Console.Write("Enter Type (A/R): ");
                        type = Console.ReadLine();
                        while (!type.Equals("A") || !type.Equals("R"))
                        {
                            if (type.Equals("A") || type.Equals("R"))
                                break;
                            Console.WriteLine("Must be A or R. Try again!");
                            Console.Write("Enter Type (A/R): ");
                            type = Console.ReadLine();
                        }
                        Console.Write("Enter Price: ");
                        p = Console.ReadLine();
                        price = float.Parse(p);
                        while (price < 0)
                        {
                            Console.WriteLine("Must not be less than 0. Try again!");
                            Console.Write("Enter Price: ");
                            p = Console.ReadLine();
                        }

                        BookCopiesBL.addBookCopies(listBookCopies, copyNumber, sequenceNumber, type, price, bookNumber);

                        Console.Write("Add another copy (y/n)?: ");
                        yn = Console.ReadLine();
                        while (!yn.Equals("y") || !yn.Equals("n"))
                        {
                            if (yn.Equals("y"))
                            {
                                Console.WriteLine("Copy Number (generated by system): {0}", count2 + 1);
                                count2++;
                                copyNumber = count2.ToString();
                                Console.WriteLine("Enter sequence number: {0}", count4+1);
                                count4++;
                                sequenceNumber = count4.ToString();
                                Console.Write("Enter Type (A/R): ");
                                type = Console.ReadLine();
                                while (!type.Equals("A") || !type.Equals("R"))
                                {
                                    if (type.Equals("A") || type.Equals("R"))
                                        break;
                                    Console.WriteLine("Must be A or R. Try again!");
                                    Console.Write("Enter Type (A/R): ");
                                    type = Console.ReadLine();
                                }
                                Console.Write("Enter Price: ");
                                p = Console.ReadLine();
                                price = float.Parse(p);
                                while (price < 0)
                                {
                                    Console.WriteLine("Must not be less than 0. Try again!");
                                    Console.Write("Enter Price: ");
                                    p = Console.ReadLine();
                                }
                                BookCopiesBL.addBookCopies(listBookCopies, copyNumber, sequenceNumber, type, price, bookNumber);
                                Console.Write("Add another copy (y/n)?: ");
                                yn = Console.ReadLine();
                            }
                            else if (yn.Equals("n"))
                                break;
                        }

                        Console.WriteLine("List of books and its copies:");

                        foreach (Book b in listBook)
                        {
                            Console.WriteLine("Book#   Title     Author   Publisher");
                            Console.WriteLine("{0}        {1}         {2}          {3}", b.BookNumber, b.Title, b.Author, b.Publisher);

                            Console.WriteLine("     Copy#   Sequence#     Type   Price");
                            foreach (BookCopies bc in listBookCopies)
                            {
                                if (b.BookNumber.Equals(bc.BookNumber))
                                {
                                    Console.WriteLine("     {0}          {1}          {2}      {3}", bc.CopyNumber, bc.SequenceNumber, bc.Type, bc.Price);
                                }
                            }
                        }
                        Console.ReadKey();

                        break;

                    case 3:
                        System.Environment.Exit(0);
                        break;
                }
            }

            Console.ReadLine();
        }
    }
}