package Q1;

import java.util.Calendar;

public class AThread extends javax.swing.JFrame {

    class Clock implements Runnable {

        @Override
        public void run() {
            try {
                for (int i = 0; i < 5; i++) {
                    Calendar now = Calendar.getInstance();
                    int h = now.get(Calendar.HOUR);
                    int m = now.get(Calendar.MINUTE);
                    int s = now.get(Calendar.SECOND);
                    jTextArea1.append("Time: " + h + ":" + m + ":" + s + "\n");
                    Thread.sleep(1000);
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }

    class Dog implements Runnable {

        @Override
        public void run() {
            try {
                for (int i = 0; i < 5; i++) {
                    jTextArea1.append("Dog: Watching, Watching, Watching" + "\n");
                    if (i == 4) {
                        Thread.sleep(1000);
                        jTextArea1.append("Person: Wow, big Dog, run run run ... " + "\n");
                        jTextArea1.append("Dog : Go Go Go ..." + "\n");
                    }
                    Thread.sleep(1000);
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }

    class Person implements Runnable {

        @Override
        public void run() {
            try {

                for (int i = 10; i <= 50; i += 10) {
                    jTextArea1.append("Person: Run " + i + " so far." + "\n");
                    if (i == 50) {
                        jTextArea1.append("Person: Safe. STOP" + "\n");
                    }
                    Thread.sleep(1000);
                }

            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }

    public AThread() {
        initComponents();
        Clock cl = new Clock();
        Person ps = new Person();
        Dog dog = new Dog();
        Thread clT = new Thread(cl);
        Thread psT = new Thread(ps);
        Thread dogT = new Thread(dog);
        try {
            clT.start();
            dogT.start();
            dogT.join();
            psT.start();
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AThread().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
